#!/bin/sh

sv start mongodb || exit 1
while ! nc -vz localhost 27017; do sleep 1; done

exec 2>&1
exec /PredictionIO/bin/predictionio-admin -Dio.prediction.base=/PredictionIO -Dsbt.log.noformat=true -Dconfig.file=/PredictionIO/conf/predictionio.conf -Dhttp.port=9000 -Dlogger.file=/PredictionIO/conf/admin-logger.xml -Dpidfile.path=/var/run/admin.pid
