#!/bin/sh

sv start elasticsearch || exit 1
sv start hbase || exit 1

until curl http://localhost:9200; do echo "waiting for ElasticSearch to come online..."; sleep 3; done

cd /hbase/bin && ./hbase shell region_status.rb 

exec 2>&1
exec /PredictionIO/bin/pio eventserver
