#!/bin/sh
exec 2>&1
exec /PredictionIO-0.7.0/bin/predictionio-scheduler -Dio.prediction.base=/PredictionIO-0.7.0 -Dsbt.log.noformat=true -Dconfig.file=/PredictionIO-0.7.0/conf/predictionio.conf -Dhttp.port=7000 -Dlogger.file=/PredictionIO-0.7.0/conf/scheduler-logger.xml -Dpidfile.path=/var/run/scheduler.pid -Dorg.quartz.properties=/PredictionIO-0.7.0/conf/quartz.properties
